name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 12.14.1
      uses: actions/setup-node@v4
      with:
        node-version: '12.14.1'
        
    - name: Install specific npm version
      run: npm install -g npm@6.14.4
        
    - name: Install dependencies
      run: |
        npm install
        npm install -D eslint@7.32.0
      
    - name: Run database migrations
      run: npm run db:up
      
    - name: Run linter
      continue-on-error: true
      run: npm run lint
      
    - name: Run tests
      run: npm test
      env:
        NODE_ENV: test

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
          build-args: |
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/car-rental-management-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/car-rental-management-api:${{ github.sha }}
