name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 12.14.1
      uses: actions/setup-node@v4
      with:
        node-version: '12.14.1'
        
    - name: Install specific npm version
      run: npm install -g npm@6.14.4
        
    - name: Install dependencies
      run: npm install
      
    - name: Run database migrations
      run: npm run db:up
      
    - name: Run linter
      run: npm run lint
      
    - name: Run tests
      run: npm test
      env:
        NODE_ENV: test